/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MerchantDashboardRouteImport } from './routes/merchant-dashboard'
import { Route as HqAdminRouteImport } from './routes/hq-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTicketRouteImport } from './routes/track.$ticket'
import { Route as PPostIdRouteImport } from './routes/p.$postId'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'

const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/merchant-dashboard',
  path: '/merchant-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HqAdminRoute = HqAdminRouteImport.update({
  id: '/hq-admin',
  path: '/hq-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTicketRoute = TrackTicketRouteImport.update({
  id: '/track/$ticket',
  path: '/track/$ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hq-admin': typeof HqAdminRoute
  '/merchant-dashboard': typeof MerchantDashboardRoute
  '/p/$postId': typeof PPostIdRoute
  '/track/$ticket': typeof TrackTicketRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hq-admin': typeof HqAdminRoute
  '/merchant-dashboard': typeof MerchantDashboardRoute
  '/p/$postId': typeof PPostIdRoute
  '/track/$ticket': typeof TrackTicketRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hq-admin': typeof HqAdminRoute
  '/merchant-dashboard': typeof MerchantDashboardRoute
  '/p/$postId': typeof PPostIdRoute
  '/track/$ticket': typeof TrackTicketRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hq-admin'
    | '/merchant-dashboard'
    | '/p/$postId'
    | '/track/$ticket'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hq-admin'
    | '/merchant-dashboard'
    | '/p/$postId'
    | '/track/$ticket'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/hq-admin'
    | '/merchant-dashboard'
    | '/p/$postId'
    | '/track/$ticket'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HqAdminRoute: typeof HqAdminRoute
  MerchantDashboardRoute: typeof MerchantDashboardRoute
  PPostIdRoute: typeof PPostIdRoute
  TrackTicketRoute: typeof TrackTicketRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/merchant-dashboard': {
      id: '/merchant-dashboard'
      path: '/merchant-dashboard'
      fullPath: '/merchant-dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq-admin': {
      id: '/hq-admin'
      path: '/hq-admin'
      fullPath: '/hq-admin'
      preLoaderRoute: typeof HqAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$ticket': {
      id: '/track/$ticket'
      path: '/track/$ticket'
      fullPath: '/track/$ticket'
      preLoaderRoute: typeof TrackTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HqAdminRoute: HqAdminRoute,
  MerchantDashboardRoute: MerchantDashboardRoute,
  PPostIdRoute: PPostIdRoute,
  TrackTicketRoute: TrackTicketRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
