/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTicketRouteImport } from './routes/track.$ticket'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTicketRoute = TrackTicketRouteImport.update({
  id: '/track/$ticket',
  path: '/track/$ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/track/$ticket': typeof TrackTicketRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/track/$ticket': typeof TrackTicketRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/track/$ticket': typeof TrackTicketRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/track/$ticket' | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/track/$ticket' | '/api/public/webhooks/razorpay'
  id: '__root__' | '/' | '/track/$ticket' | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrackTicketRoute: typeof TrackTicketRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$ticket': {
      id: '/track/$ticket'
      path: '/track/$ticket'
      fullPath: '/track/$ticket'
      preLoaderRoute: typeof TrackTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrackTicketRoute: TrackTicketRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
